## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r'E:\Data Scientist\Projects Reference\NLP Projects\Fake-New-LSTM-master\train.csv')
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [3]:
df.shape

(20800, 5)

In [8]:
df = df.dropna()

In [9]:
X = df.drop('label',axis=1)

In [10]:
y = df['label']

In [9]:
X.shape

(18285, 4)

In [10]:
y.shape

(18285,)

In [11]:
import tensorflow as tf

In [12]:
tf.__version__

'2.3.0'

In [4]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [5]:
voc_size = 5000

In [11]:
messages = X.copy()

In [12]:
messages['title']

0        House Dem Aide: We Didn’t Even See Comey’s Let...
1        FLYNN: Hillary Clinton, Big Woman on Campus - ...
2                        Why the Truth Might Get You Fired
3        15 Civilians Killed In Single US Airstrike Hav...
4        Iranian woman jailed for fictional unpublished...
                               ...                        
20795    Rapper T.I.: Trump a ’Poster Child For White S...
20796    N.F.L. Playoffs: Schedule, Matchups and Odds -...
20797    Macy’s Is Said to Receive Takeover Approach by...
20798    NATO, Russia To Hold Parallel Exercises In Bal...
20799                            What Keeps the F-35 Alive
Name: title, Length: 18285, dtype: object

In [13]:
messages.reset_index(inplace=True)

In [14]:
messages['title']

0        House Dem Aide: We Didn’t Even See Comey’s Let...
1        FLYNN: Hillary Clinton, Big Woman on Campus - ...
2                        Why the Truth Might Get You Fired
3        15 Civilians Killed In Single US Airstrike Hav...
4        Iranian woman jailed for fictional unpublished...
                               ...                        
18280    Rapper T.I.: Trump a ’Poster Child For White S...
18281    N.F.L. Playoffs: Schedule, Matchups and Odds -...
18282    Macy’s Is Said to Receive Takeover Approach by...
18283    NATO, Russia To Hold Parallel Exercises In Bal...
18284                            What Keeps the F-35 Alive
Name: title, Length: 18285, dtype: object

In [ ]:
onehot_rep = [for words in df['text']]

In [15]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [16]:
ps = PorterStemmer()

In [18]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]',' ',messages['title'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(words) for words in review if words not in set(stopwords.words('english'))]
    corpus.append(' '.join(review))
    
corpus    

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [20]:
onehot_repr = [one_hot(words, voc_size) for words in corpus]
onehot_repr

[[1099, 683, 2628, 4939, 246, 1429, 4144, 4481, 716, 218],
 [1144, 1123, 1582, 2043, 279, 3079, 963],
 [1643, 461, 3484, 1238],
 [4428, 4304, 90, 4660, 4621, 4363],
 [2911, 279, 1081, 4423, 3201, 4215, 279, 2791, 3992, 2133],
 [3579,
  1015,
  1919,
  3437,
  2552,
  2660,
  3699,
  28,
  3796,
  3326,
  972,
  2964,
  744,
  4850,
  963],
 [4096, 3919, 2506, 3720, 2, 1529, 2812, 2168, 263, 206, 254],
 [4340, 4170, 3848, 4745, 4252, 751, 2660, 4957, 263, 206, 254],
 [26, 1167, 3882, 3656, 4956, 267, 3671, 2744, 2660, 1404],
 [360, 4923, 2046, 1335, 2263, 2156, 4684, 720],
 [1804, 1418, 3645, 4305, 4853, 1648, 3139, 1128, 1327, 4144, 1812],
 [4660, 460, 246, 267, 2660, 4252],
 [716, 3585, 1798, 3741, 4361, 3918, 829, 4498, 3715],
 [4904, 3480, 3336, 4563, 4458, 4584, 4801, 263, 206, 254],
 [79, 2599, 1601, 3083, 344, 263, 206, 254],
 [1571, 182, 4344, 2501, 1459, 3625, 4162, 4992, 1370, 1901],
 [89, 2772, 1123],
 [2512, 3598, 1918, 4500, 2660, 206, 1813, 963],
 [3316, 3892, 1582, 4942, 

### Embedding Representation

In [21]:
sent_length = 20
embedd_doc = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
embedd_doc

array([[   0,    0,    0, ..., 4481,  716,  218],
       [   0,    0,    0, ...,  279, 3079,  963],
       [   0,    0,    0, ...,  461, 3484, 1238],
       ...,
       [   0,    0,    0, ...,  263,  206,  254],
       [   0,    0,    0, ..., 2454, 1187, 2684],
       [   0,    0,    0, ...,  382, 1438, 3120]])

In [22]:
embedd_doc[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1099,
        683, 2628, 4939,  246, 1429, 4144, 4481,  716,  218])

In [26]:
from tensorflow.keras.models import Sequential

In [27]:
embedding_vector_feature = 40
model = Sequential()
model.add(Embedding(voc_size,embedding_vector_feature,input_length = sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [28]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [31]:
from tensorflow.keras.layers import Bidirectional

In [32]:
embedding_vector_feature = 40
model1 = Sequential()
model1.add(Embedding(voc_size,embedding_vector_feature,input_length = sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [33]:
model1.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               112800    
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 201       
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________


In [36]:
len(embedd_doc), y.shape

(18285, (18285,))

In [38]:
import numpy as np

In [40]:
X_final = np.array(embedd_doc)
y_final = np.array(y)

In [41]:
X_final.shape, y_final.shape

((18285, 20), (18285,))

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final,y_final,test_size=0.33,random_state=42)

Model_Training

In [43]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 8s 44ms/step - loss: 0.2909 - accuracy: 0.8613 - val_loss: 0.2098 - val_accuracy: 0.9128
Epoch 2/10
192/192 [==============================] - 8s 41ms/step - loss: 0.1446 - accuracy: 0.9450 - val_loss: 0.2158 - val_accuracy: 0.9148
Epoch 3/10
192/192 [==============================] - 8s 41ms/step - loss: 0.1062 - accuracy: 0.9607 - val_loss: 0.2737 - val_accuracy: 0.9133
Epoch 4/10
192/192 [==============================] - 8s 41ms/step - loss: 0.0806 - accuracy: 0.9713 - val_loss: 0.2723 - val_accuracy: 0.9097
Epoch 5/10
192/192 [==============================] - 8s 40ms/step - loss: 0.0568 - accuracy: 0.9800 - val_loss: 0.3155 - val_accuracy: 0.9056
Epoch 6/10
192/192 [==============================] - 9s 46ms/step - loss: 0.0424 - accuracy: 0.9846 - val_loss: 0.3245 - val_accuracy: 0.9036
Epoch 7/10
192/192 [==============================] - 10s 50ms/step - loss: 0.0266 - accuracy: 0.9915 - val_loss: 0.4789 - val_accuracy: 0.910

In [44]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 6s 29ms/step - loss: 0.3490 - accuracy: 0.8328 - val_loss: 0.2030 - val_accuracy: 0.9128
Epoch 2/10
192/192 [==============================] - 5s 26ms/step - loss: 0.1520 - accuracy: 0.9371 - val_loss: 0.2059 - val_accuracy: 0.9170
Epoch 3/10
192/192 [==============================] - 5s 28ms/step - loss: 0.1049 - accuracy: 0.9598 - val_loss: 0.2374 - val_accuracy: 0.9094
Epoch 4/10
192/192 [==============================] - 6s 32ms/step - loss: 0.0716 - accuracy: 0.9755 - val_loss: 0.2595 - val_accuracy: 0.9173
Epoch 5/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0531 - accuracy: 0.9813 - val_loss: 0.3103 - val_accuracy: 0.9107
Epoch 6/10
192/192 [==============================] - 5s 27ms/step - loss: 0.0276 - accuracy: 0.9903 - val_loss: 0.3957 - val_accuracy: 0.9099
Epoch 7/10
192/192 [==============================] - 5s 27ms/step - loss: 0.0173 - accuracy: 0.9950 - val_loss: 0.4990 - val_accuracy: 0.9127

In [45]:
y_pred1 = model1.predict_classes(X_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [46]:
y_pred = model.predict_classes(X_test)

In [48]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [49]:
print(confusion_matrix(y_test, y_pred1))
confusion_matrix(y_test, y_pred)

[[3126  293]
 [ 252 2364]]


array([[3148,  271],
       [ 289, 2327]], dtype=int64)

In [50]:
print(accuracy_score(y_test, y_pred1))
accuracy_score(y_test, y_pred)

0.9096934548467275


0.9072079536039768

In [53]:
print(classification_report(y_test, y_pred1))
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      3419
           1       0.89      0.90      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035

              precision    recall  f1-score   support

           0       0.92      0.92      0.92      3419
           1       0.90      0.89      0.89      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035

